services:
  - type: web
    name: wati-work-bot
    env: python3.11
    buildCommand: |
      pip install --upgrade pip setuptools wheel
      pip install greenlet>=2.0.2 -r requirements.txt
      python -m playwright install chromium
    startCommand: python main.py
    envVars:
      - key: PLAYWRIGHT_BROWSERS_PATH
        value: /opt/render/project/src/.playwright-browsers
      - key: PORT
        value: ${PORT}
    autoDeploy: true
    plan: free
    cache: pip
