services:
  - type: web
    name: wati-auto-bot
    env: python
    plan: free
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      playwright install chromium
    startCommand: python main.py
    envVars:
      - key: PORT
        value: 10000
