services:
  - type: web
    name: wati-work-bot
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python -m playwright install chromium --with-deps
    startCommand: python main.py
    plan: free
